import Head from 'next/head'
import Image from 'next/image'
import { InboxOutlined } from '@ant-design/icons';
import { Col, Collapse, Form, Radio, RadioChangeEvent, Row, Select, Statistic, UploadProps } from 'antd';
import { message, Upload } from 'antd';
import { useState } from 'react';
import styles from '../styles/home.module.css'

const { Dragger } = Upload;
const { Panel } = Collapse;

const options = [
  { value: 'FocalLength', label: '焦距' },
  { value: 'ExposureTime', label: '曝光时间' },
  { value: 'ISO', label: '感光度' },
  { value: 'LensModel', label: '镜头', }
];

const spanMap: { [key: string]: any } = {
  LensModel: 24
}
const formatParamValue = (name: string, value: any) => {
  if (name === 'ExposureTime') {
    return value < 1 ? `1/${1 / value}` : value
  }
  return value
}

const formatOptionsLabel = (value: string) => options.find(item => item.value === value)?.label || ''


export default function Home() {
  const [exifInfo, setExifInfo] = useState<any>({})
  const [arrangement, setArrangement] = useState('horizontal');
  const [parameters, setParameters] = useState(['FocalLength', 'ExposureTime', 'ISO', 'LensModel']);

  const onChangeArrangement = (e: RadioChangeEvent) => {
    setArrangement(e.target.value);
  };

  const props: UploadProps = {
    name: 'file',
    multiple: false,
    maxCount: 1,
    action: '/api/upload',
    onChange(info) {
      // removing file
      if (info.fileList.length === 0) {
        setExifInfo({})
        return
      }
      const { status } = info.file;
      if (status !== 'uploading') {
        console.log(info.file, info.fileList);
      }
      if (status === 'done') {
        setExifInfo(info.file.response?.data?.exifInfo?.tags || {})
        message.success(`${info.file.name} file uploaded successfully.`);
      } else if (status === 'error') {
        message.error(`${info.file.name} file upload failed.`);
      }
    },
    onDrop(e) {
      console.log('Dropped files', e.dataTransfer.files);
    },
  };

  let textInfo = null
  if (arrangement === 'horizontal') {
    textInfo = <p>{parameters.map(param => `${formatOptionsLabel(param)}: ${formatParamValue(param, exifInfo[param])} `).join(' ')}</p>
  } else if (arrangement === 'vertical') {
    textInfo = parameters.map(param => <p key={param}>{`${formatOptionsLabel(param)}: ${formatParamValue(param, exifInfo[param])} `}</p>)
  }

  return (
    <>
      <Head>
        <title>Photo Exif Viewer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='container'>
        <Row gutter={24}>
          <Col span={8} >
            <div>
              <Dragger {...props} className={styles.uploader} listType="picture">
                <p className="ant-upload-drag-icon">
                  <InboxOutlined />
                </p>
                <p className="ant-upload-text">Click or drag file to this area to upload</p>
                <p className="ant-upload-hint">
                  Support for a single or bulk upload. Strictly prohibit from uploading company data or other
                  band files
                </p>
              </Dragger>
            </div>
          </Col>
          <Col span={8} >
            <Form.Item label="选取参数">
              <Select
                mode="multiple"
                showArrow
                options={options}
                value={parameters}
                onChange={value => setParameters(value)}
              />
            </Form.Item>
            <Form.Item label="文字排列方式">
              <Radio.Group onChange={onChangeArrangement} value={arrangement}>
                <Radio value={'horizontal'}>横向</Radio>
                <Radio value={'vertical'}>纵向</Radio>
              </Radio.Group>
            </Form.Item>
          </Col >

          <Col span={8} >
            {
              Object.keys(exifInfo).length === 0 ? '暂无信息，请上传图片' : <div>
                <Row>
                  {parameters.map(item => <Col key={item} span={spanMap[item] || 12}><Statistic title={formatOptionsLabel(item)} value={formatParamValue(item, exifInfo[item])} /></Col>)}
                </Row>
                <Collapse defaultActiveKey={['1']} ghost>
                  <Panel header="文本信息" key="1">
                    {textInfo}
                  </Panel>
                </Collapse>
              </div>
            }
          </Col>
        </Row>
      </main >
    </>
  )
}
